
export const categoryConstants = {
    GET_CATEGORY_REQUEST:'GET_CATEGORY_REQUEST',
    GET_CATEGORY_SUCCESS:'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_FAILURE:'GET_CATEGORY_FAILURE',
}

export const productConstants = {
    GET_PRODUCT_SUCCESS:'GET_PRODUCT_SUCCESS'
}